import "./styles/globals.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
    messages: any;
  },
  params: { locale?: string }
) {
  const locale = params?.locale || "en";
  const messages = await getMessages({ locale });

  return (
    <html className="dark" lang="en">
      <body suppressHydrationWarning>
        <Providers messages={messages} locale={locale}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
