import "./shared/styles/globals.css";
import "react-day-picker/dist/style.css";
import type { Metadata } from "next";
import { Providers } from "./providers";
import { getMessages } from "next-intl/server";

export const metadata: Metadata = {
  title: "Expenset",
  description:
    "Generated by create next app to track your incomes and expenses",
  icons: {
    icon: "/logo.png",
  },
};

export default async function RootLayout(
  {
    children,
  }: {
    children: React.ReactNode;
  },
  params: { locale?: string }
) {
  const locale = params?.locale || "en";
  const messages = await getMessages({ locale });

  return (
    <html className="dark" lang="en">
      <body suppressHydrationWarning>
        <Providers messages={messages} locale={locale}>
          {children}
        </Providers>
      </body>
    </html>
  );
}
