name: Deploy to Google Apps Script

on:
  push:
    branches: [main]
    paths:
      - 'hooks/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Set up clasp
        run: |
          cd hooks 
          echo '${{ secrets.CLASP }}' > ./.clasp.json
          echo '${{ secrets.CLASPRC }}' > ~/.clasprc.json

      - name: Install dependencies
        working-directory: hooks
        run: pnpm install
      
      - name: Push to Apps Script
        working-directory: hooks
        run: npx clasp push --force
